### ISSUE TITLE
Change to Razor Components or App-Parts

### ISSUE THREAD

**Issue by weedkiller** [WebVella/TagHelpers#2]
Hello @bzashev  since the Microsoft documentation recommends[ razor components](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-3.1) for Markup + C# code would that be a better option

`https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1` info - just launched

Just saw App Parts lot sof new stuff we can use easily, and also leverage Blazor...
https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.1

**Comment by bzashev** [comment]
Hey,
I really like the TagHelpers as functionality. But as I have some experience building JS Components, using StencilJs or Razor, and also because of the specifics of our WvField (mixing csharp and JS code), they look like a very good candidate to go Blazor.
My main concerns with the server Blazor are:
1. the lag after each interaction 
2. the lack of scalability with large size repeaters (which Fiber in Razor do quite well)

This is why we are mostly waiting to see how Blazor evolve and decide how to approach it. For now we are quite happy with the TagHelpers so there is not a big priority for this.
